### ISSUE TITLE
[3d] Allow user adjustment of flat terrain's elevation

### ISSUE THREAD

**Issue by wonder-sk** [wonder-sk/point-cloud-experiments#9]
Right now if the terrain is far away from the point cloud, the rotation behaves in a weird way because the rotation center is on the terrain.

We can solve it by allowing people to set elevation of the flat terrain - which will be useful also elsewhere.

(a proper fix for later would be to auto-pick rotation center also from point clouds or other entities)

**Comment by NEDJIMAbelgacem** [comment]
I think this is because the coordinates system of the point cloud is not the same as what's on the scene.
For example the scale might cause problems too if the point cloud dataset scale and positioning does not match with our scene.
I suggest to add some parameters in the layer properties once it is there for the position amd scale of the point scale, then use QTransform component on the root object of the point clouds 3D objects set (all the objects generated from the LoD needs to be children of that root).

**Comment by nyalldawson** [comment]
> I suggest to add some parameters in the layer properties once it is there for the position amd scale of the point scale

While this would be useful, I don't think it's the cause of the underlying issue here.

**Comment by NEDJIMAbelgacem** [comment]
> While this would be useful, I don't think it's the cause of the underlying issue here.

I understand where the issue is coming from.
The camera somewhat casts a ray from its center towards the terrain and uses that intersection as the camera center to move on the scene (You can see that by zooming into the terrain while enabling the view camera center option if the terrain is not very big).
It is more like a suggestion than a solution to the problem, I just didn't write it properly I guess.

**Comment by NEDJIMAbelgacem** [comment]
check [https://github.com/qgis/QGIS/pull/39884](url)
